function com_vaadin_terminal_gwt_DefaultWidgetSet(){var X='',eb='" for "gwt:onLoadErrorFn"',cb='" for "gwt:onPropertyErrorFn"',fb='#',Fb='.cache.js',hb='/',Eb=':',Y='::',L='<html><head><\/head><body><\/body><\/html>',_='=',gb='?',rb='ActiveXObject',bb='Bad handler "',sb='ChromeTab.ChromeFrame',Q='DOMContentLoaded',G='DUMMY',Db="GWT module 'com.vaadin.terminal.gwt.DefaultWidgetSet' may need to be (re)compiled",mb='base',kb='baseUrl',B='begin',H='body',A='bootstrap',qb='chromeframe',jb='clear.cache.gif',E='com.vaadin.terminal.gwt.DefaultWidgetSet',Cb='com.vaadin.terminal.gwt.DefaultWidgetSet.devmode.js',lb='com.vaadin.terminal.gwt.DefaultWidgetSet.nocache.js',W='com.vaadin.terminal.gwt.DefaultWidgetSet::',$='content',Hb='end',yb='gecko',zb='gecko1_8',C='gwt.codesvr.com.vaadin.terminal.gwt.DefaultWidgetSet=',D='gwt.codesvr=',db='gwt:onLoadErrorFn',ab='gwt:onPropertyErrorFn',Z='gwt:property',T='head',xb='ie6',wb='ie8',vb='ie9',I='iframe',ib='img',N='javascript',J='javascript:""',Gb='loadExternalRefs',U='meta',S='moduleRequested',R='moduleStartup',ub='msie',V='name',ob='opera',K='position:absolute; width:0; height:0; border:none; left: -1000px; top: -1000px; !important',tb='safari',M='script',Bb='selectingPermutation',F='startup',P='undefined',Ab='unknown',nb='user.agent',O='var $wnd = window.parent;',pb='webkit';var n=window;var o=document;q(A,B);function p(){var a=n.location.search;return a.indexOf(C)!=-1||a.indexOf(D)!=-1}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:E,sessionId:n.__gwtStatsSessionId,subSystem:F,evtGroup:a,millis:(new Date).getTime(),type:b})}}
com_vaadin_terminal_gwt_DefaultWidgetSet.__sendStats=q;com_vaadin_terminal_gwt_DefaultWidgetSet.__moduleName=E;com_vaadin_terminal_gwt_DefaultWidgetSet.__errFn=null;com_vaadin_terminal_gwt_DefaultWidgetSet.__moduleBase=G;com_vaadin_terminal_gwt_DefaultWidgetSet.__softPermutationId=0;com_vaadin_terminal_gwt_DefaultWidgetSet.__computePropValue=null;var r=function(){return false};var s=function(){return null};__propertyErrorFunction=null;function t(f){var g;function h(){j();return g}
function i(){j();return g.getElementsByTagName(H)[0]}
function j(){if(g){return}var a=o.createElement(I);a.src=J;a.id=E;a.style.cssText=K;a.tabIndex=-1;o.body.appendChild(a);g=a.contentDocument;if(!g){g=a.contentWindow.document}g.open();g.write(L);g.close();var b=g.getElementsByTagName(H)[0];var c=g.createElement(M);c.language=N;var d=O;c.text=d;b.appendChild(c)}
function k(a){function b(){if(typeof o.readyState==P){return typeof o.body!=P&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=false;if(b()){c=true;a()}var d;function e(){if(!c){c=true;a();if(o.removeEventListener){o.removeEventListener(Q,e,false)}if(d){clearInterval(d)}}}
if(o.addEventListener){o.addEventListener(Q,function(){e()},false)}var d=setInterval(function(){if(b()){e()}},50)}
function l(a){var b=i();var c=h().createElement(M);c.language=N;c.text=a;b.appendChild(c);b.removeChild(c)}
com_vaadin_terminal_gwt_DefaultWidgetSet.onScriptDownloaded=function(a){k(function(){l(a)})};q(R,S);var m=o.createElement(M);m.src=f;o.getElementsByTagName(T)[0].appendChild(m)}
function u(){var c={};var d;var e;var f=o.getElementsByTagName(U);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(V),k;if(j){j=j.replace(W,X);if(j.indexOf(Y)>=0){continue}if(j==Z){k=i.getAttribute($);if(k){var l,m=k.indexOf(_);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=X}c[j]=l}}else if(j==ab){k=i.getAttribute($);if(k){try{d=eval(k)}catch(a){alert(bb+k+cb)}}}else if(j==db){k=i.getAttribute($);if(k){try{e=eval(k)}catch(a){alert(bb+k+eb)}}}}}s=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;com_vaadin_terminal_gwt_DefaultWidgetSet.__errFn=e}
function v(){function e(a){var b=a.lastIndexOf(fb);if(b==-1){b=a.length}var c=a.indexOf(gb);if(c==-1){c=a.length}var d=a.lastIndexOf(hb,Math.min(c,b));return d>=0?a.substring(0,d+1):X}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(ib);b.src=a+jb;a=e(b.src)}return a}
function g(){var a=s(kb);if(a!=null){return a}return X}
function h(){var a=o.getElementsByTagName(M);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(lb)!=-1){return e(a[b].src)}}return X}
function i(){var a=o.getElementsByTagName(mb);if(a.length>0){return a[a.length-1].href}return X}
var j=g();if(j==X){j=h()}if(j==X){j=i()}if(j==X){j=e(o.location.href)}j=f(j);return j}
function w(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return com_vaadin_terminal_gwt_DefaultWidgetSet.__moduleBase+a}
function x(){var f=[];var g;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
i[nb]=function(){var c=navigator.userAgent.toLowerCase();var d=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return c.indexOf(ob)!=-1}())return ob;if(function(){return c.indexOf(pb)!=-1||function(){if(c.indexOf(qb)!=-1){return true}if(typeof window[rb]!=P){try{var b=new ActiveXObject(sb);if(b){b.registerBhoIfNeeded();return true}}catch(a){}}return false}()}())return tb;if(function(){return c.indexOf(ub)!=-1&&o.documentMode>=9}())return vb;if(function(){return c.indexOf(ub)!=-1&&o.documentMode>=8}())return wb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(c);if(a&&a.length==3)return d(a)>=6000}())return xb;if(function(){return c.indexOf(yb)!=-1}())return zb;return Ab};h[nb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};r=function(a,b){return b in h[a]};com_vaadin_terminal_gwt_DefaultWidgetSet.__computePropValue=j;q(A,Bb);if(p()){return w(Cb)}var k;try{alert(Db);return;var l=k.indexOf(Eb);if(l!=-1){g=k.substring(l+1);k=k.substring(0,l)}}catch(a){}com_vaadin_terminal_gwt_DefaultWidgetSet.__softPermutationId=g;return w(k+Fb)}
function y(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}q(Gb,B);q(Gb,Hb)}
u();com_vaadin_terminal_gwt_DefaultWidgetSet.__moduleBase=v();var z=x();y();q(A,Hb);t(z)}
com_vaadin_terminal_gwt_DefaultWidgetSet();